### ISSUE TITLE
Text is invisible on light terminal themes

### ISSUE THREAD

**Issue by monodera** [seachicken/gh-poi#121]
**Describe the bug**

When I run `gh poi`, the text colors of terminal outputs are invisible for some messages for light terminal background colors. I'm not sure if this is because of my setting of the terminal or login shell (or maybe `gh` itself), but I'd like to know if there is a way to control the text colors of the output messages.

Here are a couple of examples:

**With `Ayu Mirage` theme**:

![Screenshot 2024-04-26 at 10 56 49](https://github.com/seachicken/gh-poi/assets/90394/7369c654-abb7-46fc-8b86-b2d6e6563b98)

**With `ayu_light` theme**:

![Screenshot 2024-04-26 at 11 05 14](https://github.com/seachicken/gh-poi/assets/90394/9375f7f4-bde7-4b60-bf2f-5d68c042dcd5)

**Your Environment**
- OS: macOS 14.4.1
- gh (Check with `gh --version`): 2.47.0 and 2.48.0
- gh-poi (Check with `gh ext ls`): v0.9.8
- Terminal: iTerm2 3.4.23

**Comment by seachicken** [comment]
Thank you for you're reporting!
I had a similar issue before and it was fixed. https://github.com/seachicken/gh-poi/pull/112
`gh poi` is currently used by [fatih/color](https://github.com/fatih/color) for text colors, I think it's a problem with how to use this library, so I think it can be fixed.

`main` branch colors printing is here:
https://github.com/seachicken/gh-poi/blob/920a5e6fbc0de2c59dd865a7fede0d0a827ff368/main.go#L199

I would like to check if there is a problem only with the `white` function. Could you also check the results of `gh poi --help`?

**Comment by monodera** [comment]
yes, I still have the issue with `gh poi --help`.

![Screenshot 2024-05-02 at 20 08 44](https://github.com/seachicken/gh-poi/assets/90394/2c8a9029-c3ff-4339-b0aa-91932d9efbd9)

However, the text is visible (still a bit low contrast) on Warp terminal with Ayu Light theme 
![Screenshot 2024-05-02 at 22 02 49](https://github.com/seachicken/gh-poi/assets/90394/1f3df9b4-f887-420a-8287-5137b8c2bd82)

I haven't checked whether any difference exists in the color configurations, but it may be related to the theme configuration of my iTerm2.

**Comment by seachicken** [comment]
@monodera Thanks for reporting it, I was able to fix it. Please run `gh ext upgrade poi`.

**Comment by monodera** [comment]
It worked! Thanks for quickly fixing it.
